### ISSUE TITLE
Make the word-list space-independent

### ISSUE THREAD

**Issue by mkzero** [Bytespeicher/twitterstatus#13]
The current word-list still contains `Bytespeicher` as a synonym for hackspace.

 - [ ] `Bytespeicher` should be removed from all translations
 - [ ] A configuration option should be introduced instead

**Comment by FerranMarin** [comment]
What options should we contemplate in the configuration? I might be able to help with this one too

**Comment by mkzero** [comment]
@FerranMarin an *optional* `SPACE_NAME` that's a `string` or `list` which is taken into account for the first part of the phrase in generate_phrase would probably be enough

https://github.com/Bytespeicher/twitterstatus/blob/2eeed6aeb89761dab8207a8577e04a72f5340e92/twitterstatus.py#L40-L43

**Comment by FerranMarin** [comment]
So basically you want to remove the placeholder `Bytespeicher` with a string or list inside a file named probably "config.py"? If that's correct I'll have it done soon so all other translations can take it into account before translating

**Comment by mkzero** [comment]
@FerranMarin That's basically what I meant, but the list-item that currently exists should not be called `Bytespeicher` anymore, as this tool should be as generic as possible.

**Comment by FerranMarin** [comment]
Only problem I see with this is... it will break the translations, so went setting it up, we should take into account that it won't be possible to switch languages... at least with the implementation I went with in this [PR15](https://github.com/Bytespeicher/twitterstatus/pull/15).
