### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by mkzero** [Bytespeicher/twitterstatus#6]
We're looking for volunteers to translate the messages in `wordlist.py` into other languages like

 - [x] da_DK
 - [x] de_DE
 - [x] el_GR
 - [x] en_GB
 - [x] en_US
 - [x] es_ES
 - [x] fr_FR
 - [x] id_ID
 - [x] it_IT
 - [x] nb_NO
 - [x] nl_NL
 - [x] pt_BR
 - [x] pl_PL
 - [x] ro_RO
 - [x] ru_RU
 - [x] tr_TR

If you'd like to translate to a specific language please write a comment and when finished PR the changes with a mention to this issue. Please use IETF language tags. You can find a list with region/language examples [here](http://www.i18nguy.com/unicode/language-identifiers.html). 

You don't have to translate all phrases and you don't have to translate everything word by word - every phrase is a possible composite of one list item of every one of the lists(see [generate_phrase()](https://github.com/Bytespeicher/twitterstatus/blob/0620449aa68c379ecc26652f31fd72e4d74616e2/twitterstatus.py#L40) on how compositing currently works). 

The current en_US version is a mix of en_GB and en_US so both should be separated and the current en_US should be cleaned up.

**Comment by Maqsyo** [comment]
I'd like to translate your wordlist into de_DE :D

What's the main-language if you need en_GB too?

**Comment by Arneeeee** [comment]
I'd like to translate your wordlist into en_GB :D

**Comment by mkzero** [comment]
@Maqsyo go for it. Also added info about the en_US/en_GB problem.

**Comment by dragonhobo** [comment]
I'd like to do the fr_FR translation and help separating en_US/en_GB

**Comment by rogersec** [comment]
I'd like to add a brazilian portuguese translation. Is it ok?

**Comment by kubatyszko** [comment]
Polish translation: https://github.com/Bytespeicher/twitterstatus/pull/11

**Comment by bhctsntrk** [comment]
I'd like to do the Turkish translation.

**Comment by FerranMarin** [comment]
I'll take es_ES. Will be done hopefully by the end of today ;)

**Comment by EricBonham** [comment]
I am working on the it_IT translation :)

**Comment by kwint** [comment]
Working on nl_NL

**Comment by Lagostra** [comment]
Doing nb-NO (Norwegian) :)

**Comment by conscou** [comment]
I can do Greek!

**Comment by Chikiro** [comment]
I'd like to to ru_RU translation

**Comment by Emanon42** [comment]
If there is zh-CN (simplified Chinese), I am happy to translate.

**Comment by cfreksen** [comment]
Working on da_DK

**Comment by AndreeaEne** [comment]
Adding romanian 🇷🇴 !

**Comment by hndr91** [comment]
I'll working on id_ID

**Comment by lukyhruska96** [comment]
bb873c4

**Comment by Kietzmann** [comment]
@mkzero Please review my PR

**Comment by mkzero** [comment]
A big thanks to everyone contributing on this Hacktoberfest! :tada:
